name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    if: ${{ github.repository == 'copperlight/conan-cmake-protobuf-example' }}
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: "cmake-build"
      CC: "gcc-11"
      CXX: "g++-11"
      LANG: "en_US.UTF-8"
    steps:
      - uses: actions/checkout@v3

      - name: Install System Dependencies
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update && sudo apt-get install -y binutils-dev g++-11 libiberty-dev

          echo "==== cmake ===="
          cmake -version

          echo "==== python ===="
          python3 -V

          echo "==== conan ===="
          pip install "conan==1.59.0"
          conan --version
          if [[ ! -f ~/.conan/profiles/default ]]; then conan profile new default --detect; fi
          conan profile update settings.compiler.libcxx=libstdc++11 default

      - name: Install Project Dependencies
        run: |
          conan install . --build=missing --install-folder $BUILD_DIR
          conan source .

      - name: Build
        run: |
          cd $BUILD_DIR
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build .

      - name: Test
        run: |
          cd $BUILD_DIR
          bin/pb-example
